name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  yapf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13.5"  
      - name: Install yapf
        run: pip install yapf==0.43.0
      - name: Show YAPF config
        run: yapf --style .style.yapf --help
      - name: YAPF check
        run: yapf --diff --style .style.yapf $(find . -name "*.py")


  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.13.5" }
      - run: pip install ruff==0.6.9
      - run: ruff check .

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.13.5" }
      - run: pip install pylint
      - run: pylint --disable=all --enable=R1702,R0912,R0915,E,F .

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact --verbose --config .gitleaks.toml


  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.13.5" }
      - run: pip install pytest
      - run: pytest -q --tb=short
